services:
  treescope-core:
    container_name: treescope-core
    build: .
    image: leyya/treescope-core
    ports:
      - "5000:5000"
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - FLASK_ENV=development
      - DATABASE_URI=postgresql://postgres:postgres@172.18.0.2:5432/treescope
      # - SECRET_KEY=<THE SECRET KEY>
    depends_on:
      - treescope-core-db
  treescope-core-db:
    container_name: treescope-core-db
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=treescope
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
