services:
  treescope-core:
    container_name: treescope-core
    build: .
    image: leyya/treescope-core
    ports:
      - "5000:5000"
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - FLASK_ENV=development
      - DATABASE_URI=postgresql://postgres:postgres@treescope-core-db:5432/treescope
      # - SECRET_KEY=<THE SECRET KEY>
    volumes:
      - user_uploads:/usr/src/treescope_core/app/static/uploads
    depends_on:
      - treescope-core-db
  treescope-core-db:
    container_name: treescope-core-db
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=treescope
    volumes:
      - pg_data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - certbot_www:/var/www/certbot
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_conf:/etc/letsencrypt/
      - certbot_www:/var/www/certbot/
  mailer:
    container_name: treescope-core-mailer
    image: maildev/maildev
    ports:
      - "1080:1080"
volumes:
  pg_data: {}
  user_uploads: {}
  certbot_www: {}
  certbot_conf: {}